### ISSUE TITLE
Is it possible to use Boost ?

### ISSUE THREAD

**Issue by mario-bucev** [LPD-EPFL/CS453-2019-project#1]
The title says it all!

**Comment by srlt** [comment]
The main goal of the project is to get you a hands-on experience with *concurrent programming*.

So the rule of thumb is: you can use any external libraries, as long as they **do not solve** a concurrent programming problem.
One exception to this rule is if the external library you want to use only solves **elementary** concurrent programming problems, e.g. the library implements *mutexes* and *condition variables*.

*Boost* is a huge C++ library, and I don't know everything it contains.
If the rule of thumb stated above is not enough to determine whether the subset of *Boost* you want to use in your submission can actually be used, please reply with more info on what you need.
Or come and ask the TAs directly.

Last but not least, we are not going to install anything on the evaluation machine.
Maybe *Boost* is already there, maybe not, maybe it is not the version you want, etc.
If you are not lucky you'll have to ship it in your submission, which is limited in several ways:
  - The size of each submission is limited to 100 kB (both compressed and uncompressed).
  - The compilation time is limited to 10 s (this is probably not a problem in your case though).

**Comment by mario-bucev** [comment]
Thank you for your detailed response! Indeed I planned to use Boost for one or two concurrent data structures e.g. concurrent list. We've seen enough material to write our own version, so it shouldn't be a problem.
