### ISSUE TITLE
Minimum alignment assumption

### ISSUE THREAD

**Issue by mario-bucev** [LPD-EPFL/CS453-2019-project#2]
Hi,
Can we assume that the minimal alignment of the shared region is at least the alignment of `size_t` (i.e., at least the size of a `void *` pointer if I'm not mistaken)? This would imply that any read or write is at least pointer-aligned as well.

Thanks.

**Comment by srlt** [comment]
Hi,

The interface allows any power of 2 (i.e. 1, 2, 4, ...) for the `align` parameter of `tm_create`.
So to assume the minimal alignment of the shared region is at least `alignof(size_t)` would be a bug.

For completeness, the standard does not guarantee that `alignof(size_t) == sizeof(void*)`.
