### ISSUE TITLE
Transaction concurrency confusion

### ISSUE THREAD

**Issue by yvgny** [LPD-EPFL/CS453-2019-project#3]
For several functions, such as `bool tm_read(shared_t shared, tx_t tx, void const* source, size_t size, void* target);`, it is specified : 

> **NB:** this function can be called concurrently, concurrent calls must be made with at least a different `shared` parameter or a different `tx` parameter.

Which suggests that this function could be called concurrently with a different `shared` parameter but the same `tx`. However, in the introduction, it is stated :

> A transaction is executed on one and only one shared memory region.

What should we assume ?

Thank you very much

**Comment by srlt** [comment]
This only specifies that, for any given transaction, no two operations happen concurrently inside it.
This is what you/your library can assume.

For instance, `grading` is:
- allowed to have two threads A and B concurrently call `tm_begin` (i.e. each thread begins its own transaction), and each thread can do any `tm_read`, `tm_write`, etc concurrently with their _respective `tx` parameter_ (returned by their respective calls to `tm_begin`).
- **not** allowed to `tm_begin` a transaction from thread A, spawn another thread B, and run two `tm_read` concurrently (in threads A and B) for this transaction (i.e. with the same `tx`).
- allowed to create two different shared memory regions X and Y with `tm_create`, and if `tm_begin` on X and `tm_begin` on Y happen to return the same `tx`, the two begun transactions can still run concurrently as they are not operating on the same `shared`.

For information, `grading` only creates one shared memory region when running your library (although you should not rely on this fact in any way). I wrote the specification this way for completeness.

Now for the second quote, perhaps there is a bit of a misunderstanding.
This sentence says that, for instance if two shared memory regions X and Y exist, the _user_ (e.g. `grading`) cannot begin a transaction on X and read something on Y with it.

If this reply answers your questions/concerns, please close the issue.

**Comment by yvgny** [comment]
Thank you very much, this indeed clarifies my concerns.
