### ISSUE TITLE
Lazy conflict detection

### ISSUE THREAD

**Issue by mario-bucev** [LPD-EPFL/CS453-2019-project#5]
Hi,
Can we apply lazy conflict detection, especially for the read? That is, a read can be conflicting but the tx is allowed to continue and would be aborted at the end.

Thank you

**Comment by srlt** [comment]
As long as you do not break _isolation_ (by reading a value written by another pending transaction) or _consistency_, yes you can.

**Comment by mario-bucev** [comment]
Great, thank you (again) for the answer!
